import type { Question } from "./types";

export const mathQuestions: readonly Question[] = [
  {
    id: "math-foundation-counting-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Membilang",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Ada berapa bintang? ⭐ ⭐ ⭐",
    choices: ["2", "3", "4"],
    correctAnswer: "3",
    explanation: "Kita hitung satu per satu: satu, dua, tiga bintang.",
    status: "published",
  },
  {
    id: "math-foundation-shapes-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Bentuk",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Manakah yang berbentuk lingkaran?",
    choices: ["⚪", "🔺", "⬛"],
    correctAnswer: "⚪",
    explanation: "Lingkaran berbentuk bulat dan tidak memiliki sudut.",
    status: "published",
  },
  {
    id: "math-foundation-more-less-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Banyak dan sedikit",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Kelompok mana yang memiliki paling banyak apel?",
    choices: ["🍎", "🍎 🍎", "🍎 🍎 🍎"],
    correctAnswer: "🍎 🍎 🍎",
    explanation: "Kelompok dengan tiga apel memiliki apel paling banyak.",
    status: "published",
  },
  {
    id: "math-foundation-pattern-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Pola",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Lanjutkan pola: 🔵 🟡 🔵 🟡 ...",
    choices: ["🔵", "🟡", "🟢"],
    correctAnswer: "🔵",
    explanation: "Polanya bergantian biru, kuning, biru, kuning. Berikutnya biru.",
    status: "published",
  },
  {
    id: "math-foundation-position-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Posisi",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Burung berada di mana? 🐦\n🌳",
    choices: ["Di atas pohon", "Di bawah pohon", "Di dalam pohon"],
    correctAnswer: "Di atas pohon",
    explanation: "Burung terlihat berada di atas pohon.",
    status: "published",
  },
  {
    id: "math-a-addition-001",
    subject: "matematika",
    phase: "A",
    topic: "Penjumlahan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 7 + 5?",
    choices: ["10", "12", "13"],
    correctAnswer: "12",
    explanation: "Mulai dari 7, lalu maju 5 langkah: 8, 9, 10, 11, 12.",
    status: "published",
  },
  {
    id: "math-a-addition-002",
    subject: "matematika",
    phase: "A",
    topic: "Penjumlahan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Nara punya 8 apel dan mendapat 6 apel lagi. Berapa jumlahnya?",
    choices: ["12 apel", "14 apel", "16 apel"],
    correctAnswer: "14 apel",
    explanation: "8 apel ditambah 6 apel sama dengan 14 apel.",
    status: "published",
  },
  {
    id: "math-a-subtraction-001",
    subject: "matematika",
    phase: "A",
    topic: "Pengurangan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 15 − 7?",
    choices: ["7", "8", "9"],
    correctAnswer: "8",
    explanation: "15 dikurangi 7 sama dengan 8.",
    status: "published",
  },
  {
    id: "math-a-place-value-001",
    subject: "matematika",
    phase: "A",
    topic: "Nilai tempat",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Pada bilangan 47, angka 4 bernilai ...",
    choices: ["4", "40", "400"],
    correctAnswer: "40",
    explanation: "Angka 4 berada di tempat puluhan, sehingga nilainya 40.",
    status: "published",
  },
  {
    id: "math-a-pattern-001",
    subject: "matematika",
    phase: "A",
    topic: "Pola bilangan",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Lanjutkan pola: 2, 4, 6, 8, ...",
    choices: ["9", "10", "12"],
    correctAnswer: "10",
    explanation: "Setiap bilangan bertambah 2, jadi setelah 8 adalah 10.",
    status: "published",
  },
  {
    id: "math-b-addition-001",
    subject: "matematika",
    phase: "B",
    topic: "Penjumlahan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 248 + 175?",
    choices: ["413", "423", "433"],
    correctAnswer: "423",
    explanation: "248 + 175 = 248 + 100 + 75 = 423.",
    status: "published",
  },
  {
    id: "math-b-multiplication-001",
    subject: "matematika",
    phase: "B",
    topic: "Perkalian",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Ada 6 kotak. Setiap kotak berisi 8 pensil. Berapa semua pensil?",
    choices: ["42 pensil", "48 pensil", "56 pensil"],
    correctAnswer: "48 pensil",
    explanation: "6 kelompok berisi 8 adalah 6 × 8 = 48 pensil.",
    status: "published",
  },
  {
    id: "math-b-division-001",
    subject: "matematika",
    phase: "B",
    topic: "Pembagian",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "45 kue dibagi rata kepada 5 anak. Setiap anak mendapat ...",
    choices: ["8 kue", "9 kue", "10 kue"],
    correctAnswer: "9 kue",
    explanation: "45 ÷ 5 = 9, jadi setiap anak mendapat 9 kue.",
    status: "published",
  },
  {
    id: "math-b-fraction-001",
    subject: "matematika",
    phase: "B",
    topic: "Pecahan",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Pecahan mana yang senilai dengan 1/2?",
    choices: ["2/4", "2/3", "3/4"],
    correctAnswer: "2/4",
    explanation: "Jika pembilang dan penyebut 1/2 dikali 2, hasilnya 2/4.",
    status: "published",
  },
  {
    id: "math-b-perimeter-001",
    subject: "matematika",
    phase: "B",
    topic: "Keliling",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Persegi memiliki sisi 7 cm. Berapa kelilingnya?",
    choices: ["14 cm", "28 cm", "49 cm"],
    correctAnswer: "28 cm",
    explanation: "Keliling persegi adalah 4 × sisi, jadi 4 × 7 = 28 cm.",
    status: "published",
  },
  {
    id: "math-c-fraction-001",
    subject: "matematika",
    phase: "C",
    topic: "Pecahan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 1/3 + 1/6?",
    choices: ["1/2", "2/9", "2/6"],
    correctAnswer: "1/2",
    explanation: "1/3 sama dengan 2/6. Jadi 2/6 + 1/6 = 3/6 = 1/2.",
    status: "published",
  },
  {
    id: "math-c-decimal-001",
    subject: "matematika",
    phase: "C",
    topic: "Desimal",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 2,75 + 1,5?",
    choices: ["3,25", "4,25", "4,75"],
    correctAnswer: "4,25",
    explanation: "Sejajarkan tanda koma: 2,75 + 1,50 = 4,25.",
    status: "published",
  },
  {
    id: "math-c-percentage-001",
    subject: "matematika",
    phase: "C",
    topic: "Persentase",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa 25% dari 80?",
    choices: ["15", "20", "25"],
    correctAnswer: "20",
    explanation: "25% adalah seperempat. Seperempat dari 80 adalah 20.",
    status: "published",
  },
  {
    id: "math-c-area-001",
    subject: "matematika",
    phase: "C",
    topic: "Luas",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Sebuah persegi panjang memiliki panjang 12 cm dan lebar 5 cm. Berapa luasnya?",
    choices: ["17 cm²", "34 cm²", "60 cm²"],
    correctAnswer: "60 cm²",
    explanation: "Luas persegi panjang = panjang × lebar = 12 × 5 = 60 cm².",
    status: "published",
  },
  {
    id: "math-c-ratio-001",
    subject: "matematika",
    phase: "C",
    topic: "Perbandingan",
    difficulty: 3,
    type: "multiple-choice",
    prompt: "Perbandingan buku cerita dan komik adalah 3 : 2. Jika ada 12 buku cerita, ada berapa komik?",
    choices: ["6 komik", "8 komik", "9 komik"],
    correctAnswer: "8 komik",
    explanation: "12 adalah 4 × 3, sehingga jumlah komik adalah 4 × 2 = 8.",
    status: "published",
  },
  {
    id: "math-d-set-001",
    subject: "matematika",
    phase: "D",
    topic: "Himpunan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "A = {2, 4, 6, 8}. Manakah pernyataan yang benar?",
    choices: ["5 ∈ A", "6 ∈ A", "9 ∈ A"],
    correctAnswer: "6 ∈ A",
    explanation: "Simbol ∈ berarti anggota dari. Bilangan 6 tercantum sebagai anggota himpunan A.",
    status: "published",
  },
  {
    id: "math-d-relation-001",
    subject: "matematika",
    phase: "D",
    topic: "Relasi",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "A = {1, 2, 3} dan B = {2, 4, 6}. Pasangan mana menunjukkan relasi ‘dua kali dari’ dari A ke B?",
    choices: ["{(1,2), (2,4), (3,6)}", "{(1,4), (2,2), (3,6)}", "{(1,6), (2,4), (3,2)}"],
    correctAnswer: "{(1,2), (2,4), (3,6)}",
    explanation: "Setiap anggota B adalah dua kali anggota A: 2 = 2×1, 4 = 2×2, dan 6 = 2×3.",
    status: "published",
  },
  {
    id: "math-d-function-001",
    subject: "matematika",
    phase: "D",
    topic: "Fungsi",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Jika f(x) = 3x − 2, berapa nilai f(5)?",
    choices: ["11", "13", "15"],
    correctAnswer: "13",
    explanation: "Ganti x dengan 5: f(5) = 3(5) − 2 = 15 − 2 = 13.",
    status: "published",
  },
  {
    id: "math-d-equation-001",
    subject: "matematika",
    phase: "D",
    topic: "Persamaan linear",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa nilai x pada 2x + 5 = 15?",
    choices: ["4", "5", "6"],
    correctAnswer: "5",
    explanation: "Kurangi kedua ruas dengan 5 sehingga 2x = 10, lalu bagi 2. Jadi x = 5.",
    status: "published",
  },
  {
    id: "math-d-spldv-001",
    subject: "matematika",
    phase: "D",
    topic: "SPLDV",
    difficulty: 3,
    type: "multiple-choice",
    prompt: "x + y = 10 dan x − y = 2. Berapa nilai x dan y?",
    choices: ["x = 6, y = 4", "x = 5, y = 5", "x = 4, y = 6"],
    correctAnswer: "x = 6, y = 4",
    explanation: "Jumlahkan kedua persamaan: 2x = 12 sehingga x = 6. Substitusi memberi y = 4.",
    status: "published",
  },
] as const;
