import type { Question } from "./types";

export const mathQuestions: readonly Question[] = [
  {
    id: "math-foundation-counting-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Membilang",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Ada berapa bintang? ⭐ ⭐ ⭐",
    choices: ["2", "3", "4"],
    correctAnswer: "3",
    explanation: "Kita hitung satu per satu: satu, dua, tiga bintang.",
    status: "published",
  },
  {
    id: "math-foundation-shapes-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Bentuk",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Manakah yang berbentuk lingkaran?",
    choices: ["⚪", "🔺", "⬛"],
    correctAnswer: "⚪",
    explanation: "Lingkaran berbentuk bulat dan tidak memiliki sudut.",
    status: "published",
  },
  {
    id: "math-foundation-more-less-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Banyak dan sedikit",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Kelompok mana yang memiliki paling banyak apel?",
    choices: ["🍎", "🍎 🍎", "🍎 🍎 🍎"],
    correctAnswer: "🍎 🍎 🍎",
    explanation: "Kelompok dengan tiga apel memiliki apel paling banyak.",
    status: "published",
  },
  {
    id: "math-foundation-pattern-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Pola",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Lanjutkan pola: 🔵 🟡 🔵 🟡 ...",
    choices: ["🔵", "🟡", "🟢"],
    correctAnswer: "🔵",
    explanation: "Polanya bergantian biru, kuning, biru, kuning. Berikutnya biru.",
    status: "published",
  },
  {
    id: "math-foundation-position-001",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Posisi",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Burung berada di mana? 🐦\n🌳",
    choices: ["Di atas pohon", "Di bawah pohon", "Di dalam pohon"],
    correctAnswer: "Di atas pohon",
    explanation: "Burung terlihat berada di atas pohon.",
    status: "published",
  },
  {
    id: "math-a-addition-001",
    subject: "matematika",
    phase: "A",
    topic: "Penjumlahan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 7 + 5?",
    choices: ["10", "12", "13"],
    correctAnswer: "12",
    explanation: "Mulai dari 7, lalu maju 5 langkah: 8, 9, 10, 11, 12.",
    status: "published",
  },
  {
    id: "math-a-addition-002",
    subject: "matematika",
    phase: "A",
    topic: "Penjumlahan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Nara punya 8 apel dan mendapat 6 apel lagi. Berapa jumlahnya?",
    choices: ["12 apel", "14 apel", "16 apel"],
    correctAnswer: "14 apel",
    explanation: "8 apel ditambah 6 apel sama dengan 14 apel.",
    status: "published",
  },
  {
    id: "math-a-subtraction-001",
    subject: "matematika",
    phase: "A",
    topic: "Pengurangan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 15 − 7?",
    choices: ["7", "8", "9"],
    correctAnswer: "8",
    explanation: "15 dikurangi 7 sama dengan 8.",
    status: "published",
  },
  {
    id: "math-a-place-value-001",
    subject: "matematika",
    phase: "A",
    topic: "Nilai tempat",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Pada bilangan 47, angka 4 bernilai ...",
    choices: ["4", "40", "400"],
    correctAnswer: "40",
    explanation: "Angka 4 berada di tempat puluhan, sehingga nilainya 40.",
    status: "published",
  },
  {
    id: "math-a-pattern-001",
    subject: "matematika",
    phase: "A",
    topic: "Pola bilangan",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Lanjutkan pola: 2, 4, 6, 8, ...",
    choices: ["9", "10", "12"],
    correctAnswer: "10",
    explanation: "Setiap bilangan bertambah 2, jadi setelah 8 adalah 10.",
    status: "published",
  },
  {
    id: "math-b-addition-001",
    subject: "matematika",
    phase: "B",
    topic: "Penjumlahan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 248 + 175?",
    choices: ["413", "423", "433"],
    correctAnswer: "423",
    explanation: "248 + 175 = 248 + 100 + 75 = 423.",
    status: "published",
  },
  {
    id: "math-b-multiplication-001",
    subject: "matematika",
    phase: "B",
    topic: "Perkalian",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Ada 6 kotak. Setiap kotak berisi 8 pensil. Berapa semua pensil?",
    choices: ["42 pensil", "48 pensil", "56 pensil"],
    correctAnswer: "48 pensil",
    explanation: "6 kelompok berisi 8 adalah 6 × 8 = 48 pensil.",
    status: "published",
  },
  {
    id: "math-b-division-001",
    subject: "matematika",
    phase: "B",
    topic: "Pembagian",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "45 kue dibagi rata kepada 5 anak. Setiap anak mendapat ...",
    choices: ["8 kue", "9 kue", "10 kue"],
    correctAnswer: "9 kue",
    explanation: "45 ÷ 5 = 9, jadi setiap anak mendapat 9 kue.",
    status: "published",
  },
  {
    id: "math-b-fraction-001",
    subject: "matematika",
    phase: "B",
    topic: "Pecahan",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Pecahan mana yang senilai dengan 1/2?",
    choices: ["2/4", "2/3", "3/4"],
    correctAnswer: "2/4",
    explanation: "Jika pembilang dan penyebut 1/2 dikali 2, hasilnya 2/4.",
    status: "published",
  },
  {
    id: "math-b-perimeter-001",
    subject: "matematika",
    phase: "B",
    topic: "Keliling",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Persegi memiliki sisi 7 cm. Berapa kelilingnya?",
    choices: ["14 cm", "28 cm", "49 cm"],
    correctAnswer: "28 cm",
    explanation: "Keliling persegi adalah 4 × sisi, jadi 4 × 7 = 28 cm.",
    status: "published",
  },
  {
    id: "math-c-fraction-001",
    subject: "matematika",
    phase: "C",
    topic: "Pecahan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 1/3 + 1/6?",
    choices: ["1/2", "2/9", "2/6"],
    correctAnswer: "1/2",
    explanation: "1/3 sama dengan 2/6. Jadi 2/6 + 1/6 = 3/6 = 1/2.",
    status: "published",
  },
  {
    id: "math-c-decimal-001",
    subject: "matematika",
    phase: "C",
    topic: "Desimal",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 2,75 + 1,5?",
    choices: ["3,25", "4,25", "4,75"],
    correctAnswer: "4,25",
    explanation: "Sejajarkan tanda koma: 2,75 + 1,50 = 4,25.",
    status: "published",
  },
  {
    id: "math-c-percentage-001",
    subject: "matematika",
    phase: "C",
    topic: "Persentase",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa 25% dari 80?",
    choices: ["15", "20", "25"],
    correctAnswer: "20",
    explanation: "25% adalah seperempat. Seperempat dari 80 adalah 20.",
    status: "published",
  },
  {
    id: "math-c-area-001",
    subject: "matematika",
    phase: "C",
    topic: "Luas",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Sebuah persegi panjang memiliki panjang 12 cm dan lebar 5 cm. Berapa luasnya?",
    choices: ["17 cm²", "34 cm²", "60 cm²"],
    correctAnswer: "60 cm²",
    explanation: "Luas persegi panjang = panjang × lebar = 12 × 5 = 60 cm².",
    status: "published",
  },
  {
    id: "math-c-ratio-001",
    subject: "matematika",
    phase: "C",
    topic: "Perbandingan",
    difficulty: 3,
    type: "multiple-choice",
    prompt:
      "Perbandingan buku cerita dan komik adalah 3 : 2. Jika ada 12 buku cerita, ada berapa komik?",
    choices: ["6 komik", "8 komik", "9 komik"],
    correctAnswer: "8 komik",
    explanation: "12 adalah 4 × 3, sehingga jumlah komik adalah 4 × 2 = 8.",
    status: "published",
  },
  {
    id: "math-d-set-001",
    subject: "matematika",
    phase: "D",
    topic: "Himpunan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "A = {2, 4, 6, 8}. Manakah pernyataan yang benar?",
    choices: ["5 ∈ A", "6 ∈ A", "9 ∈ A"],
    correctAnswer: "6 ∈ A",
    explanation: "Simbol ∈ berarti anggota dari. Bilangan 6 tercantum sebagai anggota himpunan A.",
    status: "published",
  },
  {
    id: "math-d-relation-001",
    subject: "matematika",
    phase: "D",
    topic: "Relasi",
    difficulty: 1,
    type: "multiple-choice",
    prompt:
      "A = {1, 2, 3} dan B = {2, 4, 6}. Pasangan mana menunjukkan relasi ‘dua kali dari’ dari A ke B?",
    choices: ["{(1,2), (2,4), (3,6)}", "{(1,4), (2,2), (3,6)}", "{(1,6), (2,4), (3,2)}"],
    correctAnswer: "{(1,2), (2,4), (3,6)}",
    explanation: "Setiap anggota B adalah dua kali anggota A: 2 = 2×1, 4 = 2×2, dan 6 = 2×3.",
    status: "published",
  },
  {
    id: "math-d-function-001",
    subject: "matematika",
    phase: "D",
    topic: "Fungsi",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Jika f(x) = 3x − 2, berapa nilai f(5)?",
    choices: ["11", "13", "15"],
    correctAnswer: "13",
    explanation: "Ganti x dengan 5: f(5) = 3(5) − 2 = 15 − 2 = 13.",
    status: "published",
  },
  {
    id: "math-d-equation-001",
    subject: "matematika",
    phase: "D",
    topic: "Persamaan linear",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa nilai x pada 2x + 5 = 15?",
    choices: ["4", "5", "6"],
    correctAnswer: "5",
    explanation: "Kurangi kedua ruas dengan 5 sehingga 2x = 10, lalu bagi 2. Jadi x = 5.",
    status: "published",
  },
  {
    id: "math-d-spldv-001",
    subject: "matematika",
    phase: "D",
    topic: "SPLDV",
    difficulty: 3,
    type: "multiple-choice",
    prompt: "x + y = 10 dan x − y = 2. Berapa nilai x dan y?",
    choices: ["x = 6, y = 4", "x = 5, y = 5", "x = 4, y = 6"],
    correctAnswer: "x = 6, y = 4",
    explanation: "Jumlahkan kedua persamaan: 2x = 12 sehingga x = 6. Substitusi memberi y = 4.",
    status: "published",
  },
  {
    id: "math-foundation-counting-002",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Membilang",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Ada berapa ikan? 🐟 🐟 🐟 🐟 🐟",
    choices: ["4", "5", "6"],
    correctAnswer: "5",
    explanation: "Kita hitung ikan satu per satu sampai berjumlah lima.",
    status: "published",
  },
  {
    id: "math-foundation-shapes-002",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Bentuk",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Manakah yang berbentuk segitiga?",
    choices: ["⚪", "🔺", "🟦"],
    correctAnswer: "🔺",
    explanation: "Segitiga memiliki tiga sisi dan tiga sudut.",
    status: "published",
  },
  {
    id: "math-foundation-more-less-002",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Banyak dan sedikit",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Kelompok mana yang memiliki paling sedikit balon?",
    choices: ["🎈", "🎈 🎈", "🎈 🎈 🎈"],
    correctAnswer: "🎈",
    explanation: "Satu balon lebih sedikit daripada dua atau tiga balon.",
    status: "published",
  },
  {
    id: "math-foundation-pattern-002",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Pola",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Lanjutkan pola: 🟥 🟥 🟦 🟥 🟥 🟦 ...",
    choices: ["🟥", "🟦", "🟨"],
    correctAnswer: "🟥",
    explanation: "Pola ini berulang: merah, merah, biru. Setelah biru, kembali merah.",
    status: "published",
  },
  {
    id: "math-foundation-position-002",
    subject: "matematika",
    phase: "Fondasi",
    topic: "Posisi",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Perhatikan gambar: 📦 ⚽\nBola berada di mana?",
    choices: ["Di kiri kotak", "Di kanan kotak", "Di dalam kotak"],
    correctAnswer: "Di kanan kotak",
    explanation: "Bola digambar setelah kotak, sehingga posisinya di kanan kotak.",
    status: "published",
  },
  {
    id: "math-a-subtraction-002",
    subject: "matematika",
    phase: "A",
    topic: "Pengurangan",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Berapa hasil 18 − 9?",
    choices: ["8", "9", "10"],
    correctAnswer: "9",
    explanation: "Jika 18 dikurangi 9, tersisa 9.",
    status: "published",
  },
  {
    id: "math-a-place-value-002",
    subject: "matematika",
    phase: "A",
    topic: "Nilai tempat",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Pada bilangan 63, angka 6 bernilai ...",
    choices: ["6", "60", "600"],
    correctAnswer: "60",
    explanation: "Angka 6 berada di tempat puluhan, jadi nilainya 60.",
    status: "published",
  },
  {
    id: "math-a-pattern-002",
    subject: "matematika",
    phase: "A",
    topic: "Pola bilangan",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Lanjutkan pola: 5, 10, 15, ...",
    choices: ["18", "20", "25"],
    correctAnswer: "20",
    explanation: "Setiap bilangan bertambah 5. Setelah 15 adalah 20.",
    status: "published",
  },
  {
    id: "math-a-measurement-001",
    subject: "matematika",
    phase: "A",
    topic: "Pengukuran panjang",
    difficulty: 1,
    type: "multiple-choice",
    prompt: "Pensil panjangnya 9 cm. Angka mana yang menunjukkan panjang pensil?",
    choices: ["8 cm", "9 cm", "10 cm"],
    correctAnswer: "9 cm",
    explanation: "Panjang pensil sudah disebutkan, yaitu 9 cm.",
    status: "published",
  },
  {
    id: "math-a-measurement-002",
    subject: "matematika",
    phase: "A",
    topic: "Pengukuran panjang",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Buku panjangnya 20 cm, sedangkan pensil 12 cm. Mana yang lebih panjang?",
    choices: ["Buku", "Pensil", "Sama panjang"],
    correctAnswer: "Buku",
    explanation: "20 lebih besar daripada 12, jadi buku lebih panjang.",
    status: "published",
  },
  {
    id: "math-b-addition-002",
    subject: "matematika",
    phase: "B",
    topic: "Penjumlahan",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa hasil 356 + 247?",
    choices: ["593", "603", "613"],
    correctAnswer: "603",
    explanation: "356 + 200 = 556, lalu 556 + 47 = 603.",
    status: "published",
  },
  {
    id: "math-b-multiplication-002",
    subject: "matematika",
    phase: "B",
    topic: "Perkalian",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa hasil 7 × 9?",
    choices: ["56", "63", "72"],
    correctAnswer: "63",
    explanation: "7 × 9 sama dengan 63.",
    status: "published",
  },
  {
    id: "math-b-division-002",
    subject: "matematika",
    phase: "B",
    topic: "Pembagian",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa hasil 72 ÷ 8?",
    choices: ["8", "9", "10"],
    correctAnswer: "9",
    explanation: "Karena 8 × 9 = 72, maka 72 ÷ 8 = 9.",
    status: "published",
  },
  {
    id: "math-b-fraction-002",
    subject: "matematika",
    phase: "B",
    topic: "Pecahan",
    difficulty: 2,
    type: "multiple-choice",
    prompt:
      "Satu kue dibagi menjadi 4 bagian sama besar. Rani mengambil 1 bagian. Pecahan bagian Rani adalah ...",
    choices: ["1/2", "1/3", "1/4"],
    correctAnswer: "1/4",
    explanation: "Satu dari empat bagian sama besar ditulis 1/4.",
    status: "published",
  },
  {
    id: "math-b-perimeter-002",
    subject: "matematika",
    phase: "B",
    topic: "Keliling",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Sebuah persegi panjang panjangnya 9 cm dan lebarnya 4 cm. Berapa kelilingnya?",
    choices: ["13 cm", "26 cm", "36 cm"],
    correctAnswer: "26 cm",
    explanation: "Keliling = 9 + 4 + 9 + 4 = 26 cm.",
    status: "published",
  },
  {
    id: "math-c-fraction-002",
    subject: "matematika",
    phase: "C",
    topic: "Pecahan",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa hasil 3/4 − 1/4?",
    choices: ["1/4", "1/2", "2/3"],
    correctAnswer: "1/2",
    explanation: "3/4 − 1/4 = 2/4. Pecahan 2/4 disederhanakan menjadi 1/2.",
    status: "published",
  },
  {
    id: "math-c-decimal-002",
    subject: "matematika",
    phase: "C",
    topic: "Desimal",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa hasil 3,6 − 1,25?",
    choices: ["2,25", "2,35", "2,45"],
    correctAnswer: "2,35",
    explanation: "Sejajarkan koma: 3,60 − 1,25 = 2,35.",
    status: "published",
  },
  {
    id: "math-c-percentage-002",
    subject: "matematika",
    phase: "C",
    topic: "Persentase",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa 10% dari 250?",
    choices: ["20", "25", "30"],
    correctAnswer: "25",
    explanation: "10% berarti satu per sepuluh. 250 ÷ 10 = 25.",
    status: "published",
  },
  {
    id: "math-c-area-002",
    subject: "matematika",
    phase: "C",
    topic: "Luas",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Sebuah segitiga memiliki alas 10 cm dan tinggi 6 cm. Berapa luasnya?",
    choices: ["16 cm²", "30 cm²", "60 cm²"],
    correctAnswer: "30 cm²",
    explanation: "Luas segitiga = 1/2 × alas × tinggi = 1/2 × 10 × 6 = 30 cm².",
    status: "published",
  },
  {
    id: "math-c-ratio-002",
    subject: "matematika",
    phase: "C",
    topic: "Perbandingan",
    difficulty: 3,
    type: "multiple-choice",
    prompt:
      "Perbandingan kelereng merah dan biru adalah 2 : 3. Jika jumlahnya 25, ada berapa kelereng biru?",
    choices: ["10", "15", "20"],
    correctAnswer: "15",
    explanation:
      "Jumlah bagian 2 + 3 = 5. Setiap bagian bernilai 25 ÷ 5 = 5, sehingga kelereng biru 3 × 5 = 15.",
    status: "published",
  },
  {
    id: "math-d-set-002",
    subject: "matematika",
    phase: "D",
    topic: "Himpunan",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "A = {1, 2, 3} dan B = {3, 4, 5}. Himpunan A ∪ B adalah ...",
    choices: ["{1, 2, 3, 4, 5}", "{3}", "{1, 2, 4, 5}"],
    correctAnswer: "{1, 2, 3, 4, 5}",
    explanation: "Gabungan memuat semua anggota A dan B tanpa menulis anggota yang sama dua kali.",
    status: "published",
  },
  {
    id: "math-d-relation-002",
    subject: "matematika",
    phase: "D",
    topic: "Relasi",
    difficulty: 2,
    type: "multiple-choice",
    prompt:
      "A = {2, 3, 4} dan B = {1, 2, 3}. Pasangan mana menunjukkan relasi ‘satu kurang dari’ dari A ke B?",
    choices: ["{(2,1), (3,2), (4,3)}", "{(2,2), (3,3), (4,1)}", "{(2,3), (3,1), (4,2)}"],
    correctAnswer: "{(2,1), (3,2), (4,3)}",
    explanation:
      "Setiap anggota B satu kurang dari anggota A yang dipasangkan: 1 = 2 − 1, 2 = 3 − 1, dan 3 = 4 − 1.",
    status: "published",
  },
  {
    id: "math-d-function-002",
    subject: "matematika",
    phase: "D",
    topic: "Fungsi",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Jika g(x) = x + 4, berapa nilai g(−2)?",
    choices: ["−6", "2", "6"],
    correctAnswer: "2",
    explanation: "Ganti x dengan −2: g(−2) = −2 + 4 = 2.",
    status: "published",
  },
  {
    id: "math-d-equation-002",
    subject: "matematika",
    phase: "D",
    topic: "Persamaan linear",
    difficulty: 2,
    type: "multiple-choice",
    prompt: "Berapa nilai x pada 3x − 4 = 17?",
    choices: ["6", "7", "8"],
    correctAnswer: "7",
    explanation: "Tambah kedua ruas dengan 4 sehingga 3x = 21, lalu bagi 3. Jadi x = 7.",
    status: "published",
  },
  {
    id: "math-d-spldv-002",
    subject: "matematika",
    phase: "D",
    topic: "SPLDV",
    difficulty: 3,
    type: "multiple-choice",
    prompt: "x + y = 12 dan 2x + y = 19. Berapa nilai x dan y?",
    choices: ["x = 5, y = 7", "x = 7, y = 5", "x = 8, y = 4"],
    correctAnswer: "x = 7, y = 5",
    explanation:
      "Kurangi persamaan pertama dari persamaan kedua: x = 7. Lalu 7 + y = 12, jadi y = 5.",
    status: "published",
  },
] as const;
